# Generated by Django 4.1.7 on 2023-03-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=6),
        ),
    ]
