# Generated by Django 4.1.7 on 2023-03-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_item_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
